# Generated by Django 5.0.3 on 2024-03-18 22:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Recipe",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(max_length=255)),
                ("user_id", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("ingredients", models.TextField()),
                ("steps", models.TextField()),
                ("diet", models.CharField(max_length=255)),
                ("people", models.IntegerField()),
                ("foodsaved", models.IntegerField()),
            ],
            options={
                "db_table": "Recipe",
            },
        ),
    ]
